runtime: nodejs
vm: true

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

# [START handlers]
handlers:
- url: /.*
  secure: always
# [END handlers]
